### ISSUE TITLE
why would total go down?

### ISSUE THREAD

**Issue by autonome** [autonome/superflow#1]
<img width="560" alt="CleanShot 2022-01-28 at 18 15 02@2x" src="https://user-images.githubusercontent.com/50103/151591913-1ac5b9a7-8d7f-492b-8406-6f40584c2a75.png">

seems like the "total" should only ever go up?

**Comment by hackyguru** [comment]
The total indicated here pertains to the specific month. I have changed the label to 'Monthly total' to be more clear 👍
