### ISSUE TITLE
answer state language tweaks

### ISSUE THREAD

**Issue by autonome** [autonome/superflow#2]
In the graph labels, the language needs some clarifying:

* "not-accepted" makes it sound like the asker explicitly rejected answers, which isn't quite the case

* "answered" needs to be disambiguated from "answered but not accepted"

Let's use these labels and see how it looks:

* "Accepted answer"
* "No accepted answer"
* "Unanswered"

Kinda long, but let's try it.

Also, in the boxes at the top of the main page, change "Answer not accepted" to "No accepted answer".

**Comment by hackyguru** [comment]
Done, made the suggested changes :) closing the issue.
